# Manual environment deployment for testing purposes
name: MANUAL - Deploy Environment

on:
  workflow_dispatch:
    inputs:
      custom_id:
        description: "Custom Identifier (optional, defaults to Run ID)"
        required: false
        type: string
      keep_alive:
        description: "How many minutes to keep the environment alive before destroying?"
        default: "30"
        required: true
      auto_destroy:
        description: "Automatically destroy resources after timeout?"
        type: boolean
        default: true

env:
  TERRAFORM_VERSION: "1.14.4"
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      container_image: ${{ steps.set-image.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - id: set-image
        name: Set Image Name
        run: echo "image=${{ env.ACR_LOGIN_SERVER }}/ephemeral-qa-app:${{ inputs.custom_id || github.run_id }}" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ steps.set-image.outputs.image }}

  deploy:
    name: Provision
    needs: build
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      run_id: ${{ inputs.custom_id || github.run_id }}
      environment: "qa-manual"
      container_image: ${{ needs.build.outputs.container_image }}
      terraform_version: "1.14.4"
    secrets: inherit

  wait:
    name: Wait Timer
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Keep Alive Timer
        run: |
          echo "Environment will be kept alive for ${{ inputs.keep_alive }} minutes."
          sleep $(( ${{ inputs.keep_alive }} * 60 ))

  cleanup:
    name: Destroy
    needs: [build, deploy, wait]
    if: always() && inputs.auto_destroy == true && needs.deploy.result == 'success'
    uses: ./.github/workflows/reusable-cleanup.yml
    with:
      run_id: ${{ inputs.custom_id || github.run_id }}
      environment: "qa-manual"
      container_image: ${{ needs.build.outputs.container_image }}
      terraform_version: "1.14.4"
    secrets: inherit
