# Automation pipeline for continuous integration and QA environments
name: "01 - Run Ephemeral Tests"

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [main, qa]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      custom_id:
        description: "Custom Identifier (optional, defaults to Run ID)"
        required: false
        type: string

env:
  TERRAFORM_VERSION: "1.14.4"
  PYTHON_VERSION: "3.11"

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      container_image: ${{ steps.set-image.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - id: set-image
        name: Generate Image Name
        shell: bash
        run: |
          # Usamos un fallback robusto para el ID
          RUN_ID="${{ github.event.inputs.custom_id }}"
          if [ -z "$RUN_ID" ]; then
            RUN_ID="${{ github.run_id }}"
          fi

          IMAGE="${{ secrets.ACR_LOGIN_SERVER }}/ephemeral-qa-app:$RUN_ID"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "Identified image as: $IMAGE"

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ steps.set-image.outputs.image }}

  deploy:
    name: Provision
    needs: build
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      run_id: ${{ github.event.inputs.custom_id || github.run_id }}
      environment: "qa"
      container_image: ${{ needs.build.outputs.container_image }}
      terraform_version: "1.14.4"
    secrets: inherit

  test:
    name: Regression
    needs: [build, deploy]
    uses: ./.github/workflows/reusable-test.yml
    with:
      target_url: ${{ needs.deploy.outputs.app_url }}
      python_version: "3.11"
      execution_type: "CI/CD Pipeline"
      image_tag: ${{ github.event.inputs.custom_id || github.run_id }}
    secrets: inherit

  cleanup:
    name: Destroy
    needs: [build, deploy, test]
    if: always() && needs.deploy.result == 'success'
    uses: ./.github/workflows/reusable-cleanup.yml
    with:
      run_id: ${{ github.event.inputs.custom_id || github.run_id }}
      environment: "qa"
      container_image: ${{ needs.build.outputs.container_image }}
      terraform_version: "1.14.4"
    secrets: inherit
